name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install DevTools
      run: |
        npm install jest
    - name: Build
      run: |
        npm install
      env:
        CI: true
    - name: Tests
      run: |
        npm test
      env:
        CI: true
